using Trap_Intel.Domain.Abstractions;
using Trap_Intel.Domain.Shared;
using Trap_Intel.Domain.Alerts.Enums;
using Trap_Intel.Domain.Alerts.Events;
using Trap_Intel.Domain.Alerts.ValueObjects;
using Trap_Intel.Domain.Alerts.Entities;

namespace Trap_Intel.Domain.Alerts;

/// <summary>
/// Represents an alert generated by the system.
/// Tracks lifecycle from creation through resolution.
/// Owns child entities for actions, comments, notifications, and escalations.
/// </summary>
public class Alert : AggregateRoot<Guid>
{
    private List<AlertActionEntity> _actions = new();
    private List<AlertCommentEntity> _comments = new();
    private List<AlertNotificationEntity> _notifications = new();
    private List<AlertEscalationEntity> _escalations = new();

    // Private constructor for EF
    private Alert() { }

    private Alert(
        Guid id,
        Guid organizationId,
        AlertType alertType,
        AlertSeverity severity,
        string title,
        string description,
        AlertSource source)
        : base(id)
    {
        OrganizationId = organizationId;
        AlertType = alertType;
        Severity = severity;
        Priority = DeterminePriority(severity);
        Title = title;
        Description = description;
        Source = source;
        Status = AlertStatus.New;
        EscalationLevel = EscalationLevel.Level1;
        CreatedAt = DateTime.UtcNow;
        UpdatedAt = DateTime.UtcNow;
    }

    #region Properties

    /// <summary>
    /// Organization this alert belongs to.
    /// </summary>
    public Guid OrganizationId { get; private set; }

    /// <summary>
    /// Type of alert.
    /// </summary>
    public AlertType AlertType { get; private set; }

    /// <summary>
    /// Severity level.
    /// </summary>
    public AlertSeverity Severity { get; private set; }

    /// <summary>
    /// Handling priority.
    /// </summary>
    public AlertPriority Priority { get; private set; }

    /// <summary>
    /// Alert title.
    /// </summary>
    public string Title { get; private set; } = string.Empty;

    /// <summary>
    /// Detailed description.
    /// </summary>
    public string Description { get; private set; } = string.Empty;

    /// <summary>
    /// Current status.
    /// </summary>
    public AlertStatus Status { get; private set; }

    /// <summary>
    /// Source that triggered the alert.
    /// </summary>
    public AlertSource Source { get; private set; } = null!;

    /// <summary>
    /// Current escalation level.
    /// </summary>
    public EscalationLevel EscalationLevel { get; private set; }

    /// <summary>
    /// User assigned to handle this alert.
    /// </summary>
    public Guid? AssignedToUserId { get; private set; }

    /// <summary>
    /// User who acknowledged the alert.
    /// </summary>
    public Guid? AcknowledgedByUserId { get; private set; }

    /// <summary>
    /// When alert was acknowledged.
    /// </summary>
    public DateTime? AcknowledgedAt { get; private set; }

    /// <summary>
    /// User who resolved the alert.
    /// </summary>
    public Guid? ResolvedByUserId { get; private set; }

    /// <summary>
    /// When alert was resolved.
    /// </summary>
    public DateTime? ResolvedAt { get; private set; }

    /// <summary>
    /// Resolution description.
    /// </summary>
    public string? Resolution { get; private set; }

    /// <summary>
    /// Snooze configuration (if snoozed).
    /// </summary>
    public SnoozeConfig? SnoozeInfo { get; private set; }

    /// <summary>
    /// When alert was created.
    /// </summary>
    public DateTime CreatedAt { get; private set; }

    /// <summary>
    /// When alert was last updated.
    /// </summary>
    public DateTime UpdatedAt { get; private set; }

    /// <summary>
    /// When alert expires (auto-close).
    /// </summary>
    public DateTime? ExpiresAt { get; private set; }

    /// <summary>
    /// Actions taken on this alert.
    /// </summary>
    public IReadOnlyList<AlertActionEntity> Actions => _actions.AsReadOnly();

    /// <summary>
    /// Comments on this alert.
    /// </summary>
    public IReadOnlyList<AlertCommentEntity> Comments => _comments.AsReadOnly();

    /// <summary>
    /// Notifications sent for this alert.
    /// </summary>
    public IReadOnlyList<AlertNotificationEntity> Notifications => _notifications.AsReadOnly();

    /// <summary>
    /// Escalation history for this alert.
    /// </summary>
    public IReadOnlyList<AlertEscalationEntity> Escalations => _escalations.AsReadOnly();

    #endregion

    #region Factory Methods

    /// <summary>
    /// Create new alert.
    /// </summary>
    public static Result<Alert> Create(
        Guid organizationId,
        AlertType alertType,
        AlertSeverity severity,
        string title,
        string description,
        AlertSource source,
        TimeSpan? expiresIn = null)
    {
        // Validation
        if (organizationId == Guid.Empty)
            return Result.Failure<Alert>(AlertErrors.InvalidOrganizationId);

        if (string.IsNullOrWhiteSpace(title))
            return Result.Failure<Alert>(AlertErrors.InvalidTitle);

        if (string.IsNullOrWhiteSpace(description))
            return Result.Failure<Alert>(AlertErrors.InvalidDescription);

        if (source == null)
            return Result.Failure<Alert>(AlertErrors.InvalidSource);

        var alert = new Alert(
            Guid.NewGuid(),
            organizationId,
            alertType,
            severity,
            title.Trim(),
            description.Trim(),
            source);

        if (expiresIn.HasValue)
        {
            alert.ExpiresAt = DateTime.UtcNow.Add(expiresIn.Value);
        }

        // Add creation action
        alert._actions.Add(AlertActionEntity.ForCreation(alert.Id, Guid.Empty));

        // Raise event
        alert.RaiseDomainEvent(new AlertCreatedEvent(
            alert.Id,
            organizationId,
            alertType,
            severity,
            title,
            DateTime.UtcNow));

        return Result.Success(alert);
    }

    /// <summary>
    /// Create alert from high severity attack.
    /// </summary>
    public static Result<Alert> CreateFromAttack(
        Guid organizationId,
        Guid attackEventId,
        string attackType,
        string severity,
        string sourceIP,
        Guid honeypotId,
        string honeypotName)
    {
        var alertSeverity = severity.ToLower() switch
        {
            "critical" => AlertSeverity.Critical,
            "high" => AlertSeverity.High,
            "medium" => AlertSeverity.Medium,
            _ => AlertSeverity.Low
        };

        var alertType = attackType.ToLower() switch
        {
            "malware_upload" => AlertType.MalwareDetected,
            "sql_injection" => AlertType.SQLInjectionAttempt,
            "command_injection" => AlertType.CommandInjectionAttempt,
            var t when t.Contains("brute") => AlertType.BruteForceAttempt,
            _ => AlertType.HighSeverityAttack
        };

        var source = AlertSource.FromAttackEvent(attackEventId, sourceIP);

        return Create(
            organizationId,
            alertType,
            alertSeverity,
            $"{alertSeverity} Severity Attack: {attackType}",
            $"A {severity} severity {attackType} attack was detected from {sourceIP} on honeypot '{honeypotName}'",
            source,
            TimeSpan.FromDays(7));
    }

    /// <summary>
    /// Create alert for honeypot offline.
    /// </summary>
    public static Result<Alert> CreateHoneypotOffline(
        Guid organizationId,
        Guid honeypotId,
        string honeypotName,
        int missedHeartbeats)
    {
        var source = AlertSource.FromHoneypot(honeypotId, honeypotName);

        return Create(
            organizationId,
            AlertType.HoneypotOffline,
            AlertSeverity.High,
            $"Honeypot Offline: {honeypotName}",
            $"Honeypot '{honeypotName}' has missed {missedHeartbeats} consecutive heartbeats and is now offline",
            source,
            TimeSpan.FromDays(3));
    }

    /// <summary>
    /// Create alert for new threat actor.
    /// </summary>
    public static Result<Alert> CreateNewThreatActor(
        Guid organizationId,
        Guid threatActorId,
        string? alias,
        string threatLevel,
        string primaryIP)
    {
        var source = AlertSource.FromThreatActor(threatActorId, alias);

        var severity = threatLevel.ToLower() switch
        {
            "critical" or "severe" => AlertSeverity.Critical,
            "high" => AlertSeverity.High,
            "medium" => AlertSeverity.Medium,
            _ => AlertSeverity.Low
        };

        return Create(
            organizationId,
            AlertType.NewThreatActor,
            severity,
            $"New Threat Actor Identified: {alias ?? primaryIP}",
            $"A new threat actor has been identified with primary IP {primaryIP}. Threat level: {threatLevel}",
            source,
            TimeSpan.FromDays(14));
    }

    /// <summary>
    /// Reconstruct from database.
    /// </summary>
    public static Alert Reconstruct(
        Guid id,
        Guid organizationId,
        AlertType alertType,
        AlertSeverity severity,
        AlertPriority priority,
        string title,
        string description,
        AlertStatus status,
        AlertSource source,
        EscalationLevel escalationLevel,
        Guid? assignedToUserId,
        Guid? acknowledgedByUserId,
        DateTime? acknowledgedAt,
        Guid? resolvedByUserId,
        DateTime? resolvedAt,
        string? resolution,
        SnoozeConfig? snooze,
        DateTime createdAt,
        DateTime updatedAt,
        DateTime? expiresAt,
        List<AlertActionEntity>? actions = null,
        List<AlertCommentEntity>? comments = null,
        List<AlertNotificationEntity>? notifications = null,
        List<AlertEscalationEntity>? escalations = null)
    {
        return new Alert
        {
            Id = id,
            OrganizationId = organizationId,
            AlertType = alertType,
            Severity = severity,
            Priority = priority,
            Title = title,
            Description = description,
            Status = status,
            Source = source,
            EscalationLevel = escalationLevel,
            AssignedToUserId = assignedToUserId,
            AcknowledgedByUserId = acknowledgedByUserId,
            AcknowledgedAt = acknowledgedAt,
            ResolvedByUserId = resolvedByUserId,
            ResolvedAt = resolvedAt,
            Resolution = resolution,
            SnoozeInfo = snooze,
            CreatedAt = createdAt,
            UpdatedAt = updatedAt,
            ExpiresAt = expiresAt,
            _actions = actions ?? new(),
            _comments = comments ?? new(),
            _notifications = notifications ?? new(),
            _escalations = escalations ?? new()
        };
    }

    #endregion

    #region Domain Behaviors

    /// <summary>
    /// Acknowledge alert.
    /// </summary>
    public Result Acknowledge(Guid userId)
    {
        if (userId == Guid.Empty)
            return Result.Failure(AlertErrors.InvalidUserId);

        if (Status != AlertStatus.New)
            return Result.Failure(AlertErrors.AlreadyAcknowledged);

        Status = AlertStatus.Acknowledged;
        AcknowledgedByUserId = userId;
        AcknowledgedAt = DateTime.UtcNow;
        UpdatedAt = DateTime.UtcNow;

        _actions.Add(AlertActionEntity.ForAcknowledgment(Id, userId));

        var timeToAck = AcknowledgedAt.Value - CreatedAt;

        RaiseDomainEvent(new AlertAcknowledgedEvent(
            Id,
            OrganizationId,
            userId,
            timeToAck,
            DateTime.UtcNow));

        return Result.Success();
    }

    /// <summary>
    /// Start investigation.
    /// </summary>
    public Result StartInvestigation(Guid investigatorUserId)
    {
        if (investigatorUserId == Guid.Empty)
            return Result.Failure(AlertErrors.InvalidUserId);

        if (Status == AlertStatus.Resolved)
            return Result.Failure(AlertErrors.AlreadyResolved);

        Status = AlertStatus.InProgress;
        AssignedToUserId = investigatorUserId;
        UpdatedAt = DateTime.UtcNow;

        // Auto-acknowledge if not already
        if (!AcknowledgedAt.HasValue)
        {
            AcknowledgedByUserId = investigatorUserId;
            AcknowledgedAt = DateTime.UtcNow;
        }

        _actions.Add(AlertActionEntity.ForInvestigationStarted(Id, investigatorUserId));

        RaiseDomainEvent(new AlertInvestigationStartedEvent(
            Id,
            OrganizationId,
            investigatorUserId,
            DateTime.UtcNow));

        return Result.Success();
    }

    /// <summary>
    /// Escalate alert (manual).
    /// </summary>
    public Result Escalate(string reason, Guid? escalatedByUserId = null)
    {
        if (string.IsNullOrWhiteSpace(reason))
            return Result.Failure(AlertErrors.InvalidReason);

        if (EscalationLevel == EscalationLevel.External)
            return Result.Failure(AlertErrors.CannotEscalateHigher);

        if (Status == AlertStatus.Resolved)
            return Result.Failure(AlertErrors.CannotModifyResolved);

        var oldLevel = EscalationLevel;
        var newLevel = (EscalationLevel)((int)EscalationLevel + 1);

        // Create escalation record
        var escalationResult = AlertEscalationEntity.CreateManual(
            Id, oldLevel, newLevel, reason, escalatedByUserId ?? Guid.Empty, CreatedAt);

        if (escalationResult.IsFailure)
            return Result.Failure(escalationResult.Errors[0]);

        _escalations.Add(escalationResult.Value);
        
        EscalationLevel = newLevel;
        Status = AlertStatus.Escalated;
        UpdatedAt = DateTime.UtcNow;

        _actions.Add(AlertActionEntity.ForEscalation(Id, escalatedByUserId ?? Guid.Empty, reason));

        RaiseDomainEvent(new AlertEscalatedEvent(
            Id,
            OrganizationId,
            oldLevel,
            newLevel,
            reason,
            escalatedByUserId,
            DateTime.UtcNow));

        RaiseDomainEvent(new AlertEscalationRecordedEvent(
            escalationResult.Value.Id,
            Id,
            OrganizationId,
            oldLevel,
            newLevel,
            reason,
            false, // IsAutomatic
            escalatedByUserId,
            null, // SLABreached
            escalationResult.Value.TimeToEscalate,
            DateTime.UtcNow));

        return Result.Success();
    }

    /// <summary>
    /// Escalate alert automatically (SLA breach).
    /// </summary>
    public Result EscalateAutomatically(string slaName)
    {
        if (string.IsNullOrWhiteSpace(slaName))
            return Result.Failure(AlertErrors.InvalidSLAName);

        if (EscalationLevel == EscalationLevel.External)
            return Result.Failure(AlertErrors.CannotEscalateHigher);

        if (Status == AlertStatus.Resolved)
            return Result.Failure(AlertErrors.CannotModifyResolved);

        var oldLevel = EscalationLevel;
        var newLevel = (EscalationLevel)((int)EscalationLevel + 1);

        // Create automatic escalation record
        var escalationResult = AlertEscalationEntity.CreateAutomatic(
            Id, oldLevel, newLevel, slaName, CreatedAt);

        if (escalationResult.IsFailure)
            return Result.Failure(escalationResult.Errors[0]);

        _escalations.Add(escalationResult.Value);

        EscalationLevel = newLevel;
        Status = AlertStatus.Escalated;
        UpdatedAt = DateTime.UtcNow;

        var reason = $"Automatic escalation: SLA '{slaName}' breached";
        _actions.Add(AlertActionEntity.ForEscalation(Id, Guid.Empty, reason));

        RaiseDomainEvent(new AlertEscalatedEvent(
            Id,
            OrganizationId,
            oldLevel,
            newLevel,
            reason,
            null, // EscalatedByUserId
            DateTime.UtcNow));

        RaiseDomainEvent(new AlertEscalationRecordedEvent(
            escalationResult.Value.Id,
            Id,
            OrganizationId,
            oldLevel,
            newLevel,
            reason,
            true, // IsAutomatic
            null, // EscalatedByUserId
            slaName, // SLABreached
            escalationResult.Value.TimeToEscalate,
            DateTime.UtcNow));

        return Result.Success();
    }

    /// <summary>
    /// Resolve alert.
    /// </summary>
    public Result Resolve(Guid userId, string resolution)
    {
        if (userId == Guid.Empty)
            return Result.Failure(AlertErrors.InvalidUserId);

        if (string.IsNullOrWhiteSpace(resolution))
            return Result.Failure(AlertErrors.InvalidResolution);

        if (Status == AlertStatus.Resolved)
            return Result.Failure(AlertErrors.AlreadyResolved);

        Status = AlertStatus.Resolved;
        ResolvedByUserId = userId;
        ResolvedAt = DateTime.UtcNow;
        Resolution = resolution;
        UpdatedAt = DateTime.UtcNow;

        _actions.Add(AlertActionEntity.ForResolution(Id, userId, resolution));

        var timeToResolve = ResolvedAt.Value - CreatedAt;

        RaiseDomainEvent(new AlertResolvedEvent(
            Id,
            OrganizationId,
            userId,
            resolution,
            timeToResolve,
            DateTime.UtcNow));

        return Result.Success();
    }

    /// <summary>
    /// Mark as false positive.
    /// </summary>
    public Result MarkAsFalsePositive(Guid userId, string reason)
    {
        if (userId == Guid.Empty)
            return Result.Failure(AlertErrors.InvalidUserId);

        if (string.IsNullOrWhiteSpace(reason))
            return Result.Failure(AlertErrors.InvalidReason);

        Status = AlertStatus.FalsePositive;
        ResolvedByUserId = userId;
        ResolvedAt = DateTime.UtcNow;
        Resolution = $"False Positive: {reason}";
        UpdatedAt = DateTime.UtcNow;

        _actions.Add(AlertActionEntity.ForFalsePositive(Id, userId, reason));

        RaiseDomainEvent(new AlertMarkedFalsePositiveEvent(
            Id,
            OrganizationId,
            userId,
            reason,
            DateTime.UtcNow));

        return Result.Success();
    }

    /// <summary>
    /// Snooze alert.
    /// </summary>
    public Result Snooze(Guid userId, TimeSpan duration, string? reason = null)
    {
        if (userId == Guid.Empty)
            return Result.Failure(AlertErrors.InvalidUserId);

        if (duration <= TimeSpan.Zero)
            return Result.Failure(AlertErrors.InvalidSnoozeDuration);

        if (Status == AlertStatus.Snoozed)
            return Result.Failure(AlertErrors.AlreadySnoozed);

        if (Status == AlertStatus.Resolved)
            return Result.Failure(AlertErrors.CannotModifyResolved);

        Status = AlertStatus.Snoozed;
        SnoozeInfo = SnoozeConfig.Create(duration, userId, reason);
        UpdatedAt = DateTime.UtcNow;

        _actions.Add(AlertActionEntity.ForSnooze(Id, userId, SnoozeInfo.SnoozeUntil, reason));

        RaiseDomainEvent(new AlertSnoozedEvent(
            Id,
            OrganizationId,
            userId,
            SnoozeInfo.SnoozeUntil,
            reason,
            DateTime.UtcNow));

        return Result.Success();
    }

    /// <summary>
    /// Unsnooze (wake) alert.
    /// </summary>
    public Result Unsnooze()
    {
        if (Status != AlertStatus.Snoozed)
            return Result.Failure(AlertErrors.NotSnoozed);

        Status = AlertStatus.Acknowledged;
        SnoozeInfo = null;
        UpdatedAt = DateTime.UtcNow;

        _actions.Add(AlertActionEntity.ForUnsnooze(Id));

        RaiseDomainEvent(new AlertSnoozeExpiredEvent(
            Id,
            OrganizationId,
            DateTime.UtcNow));

        return Result.Success();
    }

    /// <summary>
    /// Add comment to alert.
    /// </summary>
    public Result AddComment(Guid userId, string content, bool isInternal = false, Guid? parentCommentId = null)
    {
        if (userId == Guid.Empty)
            return Result.Failure(AlertErrors.InvalidUserId);

        if (string.IsNullOrWhiteSpace(content))
            return Result.Failure(AlertErrors.InvalidComment);

        var commentResult = AlertCommentEntity.Create(Id, content, userId, isInternal, parentCommentId);
        if (commentResult.IsFailure)
            return Result.Failure(commentResult.Errors[0]);

        _comments.Add(commentResult.Value);
        UpdatedAt = DateTime.UtcNow;

        RaiseDomainEvent(new AlertCommentCreatedEvent(
            commentResult.Value.Id,
            Id,
            OrganizationId,
            userId,
            isInternal,
            parentCommentId.HasValue,
            parentCommentId,
            DateTime.UtcNow));

        return Result.Success();
    }

    /// <summary>
    /// Edit a comment.
    /// </summary>
    public Result EditComment(Guid commentId, string newContent, Guid editorUserId)
    {
        var comment = _comments.FirstOrDefault(c => c.Id == commentId);
        if (comment == null)
            return Result.Failure(AlertErrors.CommentNotFound);

        var result = comment.Edit(newContent, editorUserId);
        if (result.IsFailure)
            return result;

        UpdatedAt = DateTime.UtcNow;

        RaiseDomainEvent(new AlertCommentEditedEvent(
            commentId,
            Id,
            OrganizationId,
            editorUserId,
            DateTime.UtcNow));

        return Result.Success();
    }

    /// <summary>
    /// Delete a comment.
    /// </summary>
    public Result DeleteComment(Guid commentId, Guid deleterUserId)
    {
        var comment = _comments.FirstOrDefault(c => c.Id == commentId);
        if (comment == null)
            return Result.Failure(AlertErrors.CommentNotFound);

        var result = comment.Delete(deleterUserId);
        if (result.IsFailure)
            return result;

        UpdatedAt = DateTime.UtcNow;

        RaiseDomainEvent(new AlertCommentDeletedEvent(
            commentId,
            Id,
            OrganizationId,
            deleterUserId,
            DateTime.UtcNow));

        return Result.Success();
    }

    /// <summary>
    /// Assign to user.
    /// </summary>
    public Result AssignTo(Guid userId, Guid assignedByUserId)
    {
        if (userId == Guid.Empty)
            return Result.Failure(AlertErrors.InvalidUserId);

        if (AssignedToUserId == userId)
            return Result.Failure(AlertErrors.SelfAssignment);

        var oldAssignee = AssignedToUserId;
        AssignedToUserId = userId;
        UpdatedAt = DateTime.UtcNow;

        _actions.Add(AlertActionEntity.ForAssignment(Id, assignedByUserId, userId));

        RaiseDomainEvent(new AlertAssignedEvent(
            Id,
            OrganizationId,
            oldAssignee,
            userId,
            DateTime.UtcNow));

        return Result.Success();
    }

    /// <summary>
    /// Change severity.
    /// </summary>
    public Result ChangeSeverity(AlertSeverity newSeverity, string reason, Guid changedByUserId)
    {
        if (string.IsNullOrWhiteSpace(reason))
            return Result.Failure(AlertErrors.InvalidReason);

        if (Severity == newSeverity)
            return Result.Success();

        var oldSeverity = Severity;
        Severity = newSeverity;
        Priority = DeterminePriority(newSeverity);
        UpdatedAt = DateTime.UtcNow;

        _actions.Add(AlertActionEntity.ForSeverityChange(
            Id, changedByUserId, oldSeverity.ToString(), newSeverity.ToString(), reason));

        RaiseDomainEvent(new AlertSeverityChangedEvent(
            Id,
            OrganizationId,
            oldSeverity,
            newSeverity,
            reason,
            DateTime.UtcNow));

        return Result.Success();
    }

    /// <summary>
    /// Queue notification for this alert.
    /// </summary>
    public Result QueueNotification(
        NotificationChannel channel,
        NotificationTrigger trigger,
        List<string> recipients,
        string? subject = null,
        string? bodyPreview = null)
    {
        var notificationResult = AlertNotificationEntity.Create(
            Id, channel, trigger, recipients, subject, bodyPreview);

        if (notificationResult.IsFailure)
            return Result.Failure(notificationResult.Errors[0]);

        _notifications.Add(notificationResult.Value);

        RaiseDomainEvent(new AlertNotificationQueuedEvent(
            notificationResult.Value.Id,
            Id,
            OrganizationId,
            channel,
            trigger,
            recipients.Count,
            DateTime.UtcNow));

        return Result.Success();
    }

    /// <summary>
    /// Mark notification as sent.
    /// </summary>
    public Result MarkNotificationSent(Guid notificationId, string? externalMessageId = null)
    {
        var notification = _notifications.FirstOrDefault(n => n.Id == notificationId);
        if (notification == null)
            return Result.Failure(AlertErrors.NotificationNotFound);

        return notification.MarkAsSent(externalMessageId);
    }

    /// <summary>
    /// Mark notification as delivered.
    /// </summary>
    public Result MarkNotificationDelivered(Guid notificationId, string? providerResponse = null)
    {
        var notification = _notifications.FirstOrDefault(n => n.Id == notificationId);
        if (notification == null)
            return Result.Failure(AlertErrors.NotificationNotFound);

        var result = notification.MarkAsDelivered(providerResponse);
        if (result.IsSuccess)
        {
            RaiseDomainEvent(new AlertNotificationDeliveredEvent(
                notificationId,
                Id,
                OrganizationId,
                notification.Channel,
                notification.ExternalMessageId,
                notification.GetTimeToDelivery() ?? TimeSpan.Zero,
                DateTime.UtcNow));
        }

        return result;
    }

    /// <summary>
    /// Mark notification as failed.
    /// </summary>
    public Result MarkNotificationFailed(Guid notificationId, string reason)
    {
        var notification = _notifications.FirstOrDefault(n => n.Id == notificationId);
        if (notification == null)
            return Result.Failure(AlertErrors.NotificationNotFound);

        var result = notification.MarkAsFailed(reason);
        if (result.IsSuccess)
        {
            RaiseDomainEvent(new AlertNotificationFailedEvent(
                notificationId,
                Id,
                OrganizationId,
                notification.Channel,
                reason,
                notification.RetryCount,
                notification.CanRetry(),
                DateTime.UtcNow));
        }

        return result;
    }

    /// <summary>
    /// Expire alert (auto-close).
    /// </summary>
    public Result Expire()
    {
        if (Status == AlertStatus.Resolved)
            return Result.Success();

        Status = AlertStatus.Expired;
        ResolvedAt = DateTime.UtcNow;
        Resolution = "Auto-expired due to age";
        UpdatedAt = DateTime.UtcNow;

        _actions.Add(AlertActionEntity.ForExpiration(Id));

        RaiseDomainEvent(new AlertExpiredEvent(
            Id,
            OrganizationId,
            DateTime.UtcNow - CreatedAt,
            DateTime.UtcNow));

        return Result.Success();
    }

    #endregion

    #region Query Helpers

    /// <summary>
    /// Check if alert is open.
    /// </summary>
    public bool IsOpen() => Status != AlertStatus.Resolved && 
                            Status != AlertStatus.FalsePositive && 
                            Status != AlertStatus.Expired;

    /// <summary>
    /// Check if snooze expired.
    /// </summary>
    public bool IsSnoozeExpired() => Status == AlertStatus.Snoozed && 
                                      SnoozeInfo != null && 
                                      SnoozeInfo.IsExpired;

    /// <summary>
    /// Check if alert is expired.
    /// </summary>
    public bool IsExpired() => ExpiresAt.HasValue && DateTime.UtcNow >= ExpiresAt.Value;

    /// <summary>
    /// Get time since creation.
    /// </summary>
    public TimeSpan GetAge() => DateTime.UtcNow - CreatedAt;

    /// <summary>
    /// Get time to acknowledge (null if not acknowledged).
    /// </summary>
    public TimeSpan? GetTimeToAcknowledge() => AcknowledgedAt.HasValue 
        ? AcknowledgedAt.Value - CreatedAt 
        : null;

    /// <summary>
    /// Get time to resolve (null if not resolved).
    /// </summary>
    public TimeSpan? GetTimeToResolve() => ResolvedAt.HasValue 
        ? ResolvedAt.Value - CreatedAt 
        : null;

    /// <summary>
    /// Get visible comments (excludes deleted and internal for external users).
    /// </summary>
    public IReadOnlyList<AlertCommentEntity> GetVisibleComments(bool includeInternal = false)
    {
        return _comments
            .Where(c => !c.IsDeleted && (includeInternal || !c.IsInternal))
            .ToList()
            .AsReadOnly();
    }

    /// <summary>
    /// Get comment by ID.
    /// </summary>
    public AlertCommentEntity? GetComment(Guid commentId)
        => _comments.FirstOrDefault(c => c.Id == commentId);

    /// <summary>
    /// Get notification by ID.
    /// </summary>
    public AlertNotificationEntity? GetNotification(Guid notificationId)
        => _notifications.FirstOrDefault(n => n.Id == notificationId);

    /// <summary>
    /// Get pending notifications.
    /// </summary>
    public IReadOnlyList<AlertNotificationEntity> GetPendingNotifications()
        => _notifications.Where(n => n.IsPending()).ToList().AsReadOnly();

    /// <summary>
    /// Get failed notifications that can be retried.
    /// </summary>
    public IReadOnlyList<AlertNotificationEntity> GetRetryableNotifications()
        => _notifications.Where(n => n.CanRetry()).ToList().AsReadOnly();

    /// <summary>
    /// Get escalation history ordered by date.
    /// </summary>
    public IReadOnlyList<AlertEscalationEntity> GetEscalationHistory()
        => _escalations.OrderBy(e => e.EscalatedAt).ToList().AsReadOnly();

    /// <summary>
    /// Get latest escalation.
    /// </summary>
    public AlertEscalationEntity? GetLatestEscalation()
        => _escalations.OrderByDescending(e => e.EscalatedAt).FirstOrDefault();

    /// <summary>
    /// Check if alert has been escalated.
    /// </summary>
    public bool HasBeenEscalated() => _escalations.Count > 0;

    /// <summary>
    /// Get number of escalations.
    /// </summary>
    public int GetEscalationCount() => _escalations.Count;

    /// <summary>
    /// Get actions of a specific type.
    /// </summary>
    public IReadOnlyList<AlertActionEntity> GetActionsByType(AlertActionType actionType)
        => _actions.Where(a => a.ActionType == actionType).ToList().AsReadOnly();

    /// <summary>
    /// Get total comment count (excluding deleted).
    /// </summary>
    public int GetCommentCount() => _comments.Count(c => !c.IsDeleted);

    /// <summary>
    /// Get channels that have been successfully notified.
    /// </summary>
    public IReadOnlyList<NotificationChannel> GetNotifiedChannels()
        => _notifications
            .Where(n => n.IsSuccessful())
            .Select(n => n.Channel)
            .Distinct()
            .ToList()
            .AsReadOnly();

    #endregion

    #region Private Methods

    private static AlertPriority DeterminePriority(AlertSeverity severity)
    {
        return severity switch
        {
            AlertSeverity.Critical => AlertPriority.Emergency,
            AlertSeverity.High => AlertPriority.Urgent,
            AlertSeverity.Medium => AlertPriority.High,
            AlertSeverity.Low => AlertPriority.Normal,
            _ => AlertPriority.Low
        };
    }

    #endregion
}
