using Microsoft.AspNetCore.Identity;
using Trap_Intel.Infrastructure.Authentication.Identity;

namespace Trap_Intel.Infrastructure.Authentication.Services;

/// <summary>
/// BCrypt implementation of ASP.NET Core Identity password hasher.
/// This allows UserManager<ApplicationUser> to authenticate users
/// using the same BCrypt hashes generated by the application's
/// PasswordHashingService and database seeders.
/// </summary>
public sealed class BCryptPasswordHasher : IPasswordHasher<ApplicationUser>
{
    private const int WorkFactor = 12;

    /// <summary>
    /// Creates a BCrypt hash for the provided password.
    /// </summary>
    public string HashPassword(ApplicationUser user, string password)
    {
        ArgumentNullException.ThrowIfNull(user);
        ArgumentException.ThrowIfNullOrWhiteSpace(password);

        return BCrypt.Net.BCrypt.HashPassword(password, WorkFactor);
    }

    /// <summary>
    /// Verifies a provided password against a stored BCrypt hash.
    /// </summary>
    public Microsoft.AspNetCore.Identity.PasswordVerificationResult VerifyHashedPassword(
        ApplicationUser user,
        string hashedPassword,
        string providedPassword)
    {
      Console.WriteLine("=== BCrypt Verify Called ===");
Console.WriteLine($"Hash: {hashedPassword}");
Console.WriteLine($"Password: {providedPassword}");
        ArgumentNullException.ThrowIfNull(user);
        ArgumentException.ThrowIfNullOrWhiteSpace(hashedPassword);
        ArgumentException.ThrowIfNullOrWhiteSpace(providedPassword);

        try
        {
            var isValid = BCrypt.Net.BCrypt.Verify(
                providedPassword,
                hashedPassword);

            if (!isValid)
            {
                return Microsoft.AspNetCore.Identity.PasswordVerificationResult.Failed;
            }

            var needsRehash = BCrypt.Net.BCrypt.PasswordNeedsRehash(
                hashedPassword,
                WorkFactor);

            return needsRehash
                ? Microsoft.AspNetCore.Identity.PasswordVerificationResult.SuccessRehashNeeded
                : Microsoft.AspNetCore.Identity.PasswordVerificationResult.Success;
        }
        catch (BCrypt.Net.SaltParseException)
        {
            // Invalid or corrupted hash
            return Microsoft.AspNetCore.Identity.PasswordVerificationResult.Failed;
        }
    }
}